// 계정
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAILURE = "USER_SIGN_UP_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const GET_USERLIST = "GET_USERLIST";
export const GET_USERLIST_SUCCESS = "GET_USERLIST_SUCCESS";
export const GET_USERLIST_FAILURE = "GET_USERLIST_FAILURE";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const FORCE_PRIVILEGE = "FORCE_PRIVILEGE";
export const FORCE_PRIVILEGE_SUCCESS = "FORCE_PRIVILEGE_SUCEESS";
export const FORCE_PRIVILEGE_FAILURE = "FORCE_PRIVILEGE_FAILURE";

// 아트 관련
export const GET_ARTLIST = "GET_ARTLIST";
export const GET_ARTLIST_SUCCESS = "GET_ARTLIST_SUCCESS";
export const GET_ARTLIST_FAILURE = "GET_ARTLIST_FAILURE";

export const GET_ART = "GET_ART";
export const GET_ART_SUCCESS = "GET_ART_SUCCESS";
export const GET_ART_FAILURE = "GET_ART_FAILURE";

export const UPLOAD_ART = "UPLOAD_ART";
export const UPLOAD_ART_SUCCESS = "UPLOAD_ART_SUCCESS";
export const UPLOAD_ART_FAILURE = "UPLOAD_ART_FAILURE";

export const MODIFY_ART = "MODIFY_ART";
export const MODIFY_ART_SUCCESS = "MODIFY_ART_SUCCESS";
export const MODIFY_ART_FAILURE = "MODIFY_ART_FAILURE";

export const DELETE_ART = "DELETE_ART";
export const DELETE_ART_SUCCESS = "DELETE_ART_SUCCESS";
export const DELETE_ART_FAILURE = "DELETE_ART_FAILURE";

export const INIT_ART = "INIT_ART";

export const GET_USERART = "GET_USERART";
export const GET_USERART_SUCCESS = "GET_USERART_SUCCESS";
export const GET_USERART_FAILURE = "GET_USERART_FAILURE";


// 게시물 등록

export const INIT_BOARD = "INIT_BOARD";
export const GET_BOARDLIST = "GET_BOARDLIST";
export const GET_BOARDLIST_SUCCESS = "GET_BOARDLIST_SUCCESS";
export const GET_BOARDLIST_FAILURE = "GET_BOARDLIST_FAILURE";

export const GET_BOARD = "GET_BOARD";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_FAILURE = "GET_BOARD_FAILURE";

export const UPLOAD_BOARD = "UPLOAD_BOARD";
export const UPLOAD_BOARD_SUCCESS = "UPLOAD_BOARD_SUCCESS";
export const UPLOAD_BOARD_FAILURE = "UPLOAD_BOARD_FAILURE";

export const MODIFY_BOARD = "MODIFY_BOARD";
export const MODIFY_BOARD_SUCCESS = "MODIFY_BOARD_SUCCESS";
export const MODIFY_BOARD_FAILURE = "MODIFY_BOARD_FAILURE";

export const DELETE_BOARD = "DELETE_BOARD";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE";

export const GET_USERBOARD = "GET_USERBOARD";
export const GET_USERBOARD_SUCCESS = "GET_USERBOARD_SUCCESS";
export const GET_USERBOARD_FAILURE = "GET_USERBOARD_FAILURE";

// 배우기 관련
export const GET_LEARNLIST = "GET_LEARNLIST";
export const GET_LEARNLIST_SUCCESS = "GET_LEARNLIST_SUCCESS";
export const GET_LEARNLIST_FAILURE = "GET_LEARNLIST_FAILURE";

export const GET_LEARN = "GET_LEARN";
export const GET_LEARN_SUCCESS = "GET_LEARN_SUCCESS";
export const GET_LEARN_FAILURE = "GET_LEARN_FAILURE";

export const UPLOAD_LEARN = "UPLOAD_LEARN";
export const UPLOAD_LEARN_SUCCESS = "UPLOAD_LEARN_SUCCESS";
export const UPLOAD_LEARN_FAILURE = "UPLOAD_LEARN_FAILURE";

export const MODIFY_LEARN = "MODIFY_LEARN";
export const MODIFY_LEARN_SUCCESS = "MODIFY_LEARN_SUCCESS";
export const MODIFY_LEARN_FAILURE = "MODIFY_LEARN_FAILURE";

export const DELETE_LEARN = "DELETE_LEARN";
export const DELETE_LEARN_SUCCESS = "DELETE_LEARN_SUCCESS";
export const DELETE_LEARN_FAILURE = "DELETE_LEARN_FAILURE";

export const GET_USERLEARN = "GET_USERLEARN";
export const GET_USERLEARN_SUCCESS = "GET_USERLEARN_SUCCESS";
export const GET_USERLEARN_FAILURE = "GET_USERLEARN_FAILURE";